apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvstore
spec:
  selector:
    matchLabels:
      app: kvstore
  replicas: 1
  template:
    metadata:
      labels:
        app: kvstore
    spec:
      containers:
      - name: kvstore
        image: abhirockzz/kvstore:latest
        volumeMounts:
        - mountPath: /data
          name: data-volume
        ports:
        - containerPort: 8080
      volumes:
        - name: data-volume
          emptyDir: {}
